Vagrant.configure("2") do |config|

  # Global VM settings
  # ------------------------------

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", 1]
  end

  # centos6 VM
  # ------------------------------

  config.vm.define "centos5" do |centos5|
    centos5.vm.hostname = "centos5"
    centos5.vm.box = "CentOS-5.11-x86_64"
    centos5.vm.box_url = "../boxes/CentOS-5.11.x86_64.box"
    centos5.vm.network :private_network, ip: "192.168.33.10"
    centos5.vm.synced_folder ".", "/home/vagrant/share"
  end

  # centos6 VM
  # ------------------------------

  config.vm.define "centos6" do |centos6|
    centos6.vm.hostname = "centos6"
    centos6.vm.box = "CentOS-6.6-x86_64"
    centos6.vm.box_url = "../boxes/CentOS-6.6.x86_64.box"
    centos6.vm.network :private_network, ip: "192.168.33.11"
    centos6.vm.synced_folder ".", "/home/vagrant/share"
  end

  # centos7 VM
  # ------------------------------

  config.vm.define "centos7" do |centos7|
    centos7.vm.hostname = "centos7"
    centos7.vm.box = "CentOS-7.0.1406-x86_64"
    centos7.vm.box_url = "../boxes/CentOS-7.0.1406.x86_64.box"
    centos7.vm.network :private_network, ip: "192.168.33.12"
    centos7.vm.synced_folder ".", "/home/vagrant/share"
  end

end
